Ignore ghost non-regular files.
RPMs in Fedora 20 contain /var/run and /var/lock, as symlinks, marked
%ghost.  The old code would create these as regular files which would
then cause a failure if something was created inside them.

You would see an error like this:

Fatal error: exception Unix.Unix_error(8, "mkdir", "/tmp/supermineab65b098ada401348c6f448e9119504.tmp/root//var/run")

The new code just ignores these files.  With -v it will print a
message like this:

ignoring ghost non-regular file /var/lock (mode 0120777) from package /tmp/supermin63b9e24946f33f9b16247d063fa7e488.tmp/filesystem-3.2-16.fc20.x86_64.rpm
ignoring ghost non-regular file /var/run (mode 0120777) from package /tmp/supermin63b9e24946f33f9b16247d063fa7e488.tmp/filesystem-3.2-16.fc20.x86_64.rpm